# Generated by Django 4.1.7 on 2023-03-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_title_category_type_alter_resource_img_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='api_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
