# Generated by Django 4.1.7 on 2023-03-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_resource_api_id_alter_resource_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='api_id',
            field=models.CharField(max_length=50),
        ),
    ]
