# Generated by Django 4.1.7 on 2023-03-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_resource_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_stories',
            field=models.ManyToManyField(related_name='users', to='books.resource'),
        ),
    ]
