# Generated by Django 4.1.7 on 2023-03-08 14:21

from django.db import migrations
import csv


def import_items(apps, schema_editor):
    with open('sample_books.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            pass

    parsed_file = parsed_file.split('\n')
    Resource = apps.get_model('books', 'Resource')
    for resource in Resource.objects.all():
        resource.name = '%s %s' % (resource.first_name, resource.last_name)
        resource.save()


class Migration(migrations.Migration):

    dependencies = [
        ('books',
         '0002_category_alter_resource_options_resource_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(import_items),
    ]
